#!/bin/sh

mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs devtmpfs /dev

# Attempt to get /dev/pts for dropbear. But it doesn't help.
mount -a

# TODO: Dropbear freaks out when can't write its keys
mount -o remount,rw /
