#!/bin/sh

case "$1" in
start)
    echo "Starting WiFi..."

    killall wpa_supplicant 2>/dev/null
    killall udhcpc 2>/dev/null

    rm -rf /run/wpa_supplicant/*
    mkdir -p /run/wpa_supplicant

    # 1. bring interface up
    ip link set wlan0 up

    # 2. start WPA
    wpa_supplicant -B \
        -i wlan0 \
        -c /etc/wpa_supplicant.conf

    # 3. get IP
    udhcpc -i wlan0
    ;;
stop)
    killall wpa_supplicant
    killall udhcpc
    ;;
esac
